In [2]:
import os 
import numpy as np

In [17]:
#user_liking
#user_category
#photo_category
#YT_category --> identified with posted most 
categories = os.listdir('../Data/Image/ImageALL')

In [18]:
photoSum = 0
for category in categories:
    photoSum += len(os.listdir('../Data/Image/ImageALL/'+category))
photoSum

83227

In [19]:
photo_category = np.zeros((photoSum,17))
ImgLists = []
i = 0 
for category in categories:
    ImgList = os.listdir('../Data/Image/ImageALL/'+category)
    ImgLists += ImgList
    if ',' in category: #複數的category 
        multi_category = [int(single)-1 for single in category.split(',')]
        print(multi_category)
        for ci in range(len(ImgList)):
            for single in multi_category:
                photo_category[i+ci][single] = 1
        print(photo_category[i:i+ci+1])
        i += ci+1
    else:
        single = int(category)-1
        print(single)
        for ci in range(len(ImgList)):
            photo_category[i+ci][single] = 1
        print(photo_category[i:i+ci+1])
        i += ci+1     

0
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
[0, 9]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
[0, 10]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
[0, 11]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
[0, 11, 12]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]]
[0, 13]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[0, 14]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [9]:
len(ImgList)

83227

In [27]:
np.save('../Data/npy/photo_category',photo_category)

In [29]:
np.load('../Data/npy/photo_category.npy').shape

(83227, 17)

In [32]:
len(ImgLists)

83227

In [35]:
ImgLists = np.array(ImgLists)
np.save('../Data/npy/ImgLists',ImgLists)

In [37]:
np.load('../Data/npy/ImgLists.npy').shape

(83227,)

In [38]:
# YT_category
dictImg = {}
for i in range(len(ImgLists)):
    dictImg[ImgLists[i]] = photo_category[i]

In [40]:
YT_category = np.zeros((88,17))
YTs = os.listdir('../Data/Image/ImageYts/')
for i in range(len(YTs)):
    Imgs = os.listdir('../Data/Image/ImageYts/'+YTs[i])
    for Img in Imgs:
        YT_category[i] += dictImg[Img]

In [48]:
YT_category

array([[4.000e+00, 1.100e+01, 3.000e+00, ..., 0.000e+00, 2.000e+00,
        1.000e+00],
       [3.000e+00, 7.330e+02, 1.342e+03, ..., 0.000e+00, 1.000e+00,
        4.000e+00],
       [0.000e+00, 4.700e+01, 3.000e+00, ..., 1.000e+00, 0.000e+00,
        1.000e+00],
       ...,
       [8.210e+02, 0.000e+00, 1.200e+01, ..., 1.000e+00, 1.000e+01,
        3.110e+02],
       [1.000e+00, 4.000e+00, 1.033e+03, ..., 0.000e+00, 0.000e+00,
        2.000e+00],
       [2.000e+00, 9.000e+00, 6.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00]])

In [65]:
YT_Normcategory = np.zeros((88,17))
YT_NormSum_category = np.zeros((88,17))
for i in range(len(YT_category)):
    YT_Normcategory[i] = YT_category[i]/np.sum(YT_category[i])
    YT_NormSum_category[i] = YT_category[i]/np.max(YT_category[i])

In [67]:
np.save('../Data/npy/YT_category',YT_category)
np.save('../Data/npy/YT_Normcategory',YT_Normcategory)
np.save('../Data/npy/YT_NormSum_category',YT_NormSum_category)

In [64]:
for i in range(len(YT_Normcategory)):
    if np.max(YT_Normcategory[i]) < 0.4:
        print(i, ' ',np.max(YT_Normcategory[i]))
        print(YT_Normcategory[i])

5   0.2026578073089701
[0.08305648 0.07973422 0.09966777 0.10631229 0.00664452 0.
 0.09966777 0.02990033 0.0166113  0.07973422 0.00664452 0.01993355
 0.03986711 0.0166113  0.04651163 0.06644518 0.20265781]
25   0.21004098360655737
[0.16290984 0.00102459 0.11168033 0.01639344 0.0522541  0.01229508
 0.07479508 0.         0.00102459 0.00102459 0.01434426 0.13217213
 0.02663934 0.18032787 0.00102459 0.00204918 0.21004098]
30   0.36
[0.36 0.02 0.31 0.17 0.   0.   0.01 0.   0.   0.01 0.   0.01 0.09 0.01
 0.   0.01 0.  ]
45   0.22637106184364061
[0.02567095 0.15985998 0.22637106 0.09451575 0.06534422 0.
 0.01866978 0.01866978 0.         0.0630105  0.00583431 0.18436406
 0.12135356 0.00233372 0.         0.00583431 0.00816803]
56   0.25301204819277107
[0.07654146 0.2182849  0.0042523  0.12615167 0.00283487 0.00070872
 0.03968816 0.0042523  0.         0.00496102 0.00070872 0.25301205
 0.19631467 0.05527994 0.         0.00283487 0.01417434]
62   0.3333333333333333
[0.33333333 0.33333333 0.       

In [72]:
YT_NormSum_category[74]

array([0.02293578, 0.41284404, 0.16055046, 0.55504587, 0.09633028,
       0.58715596, 0.11926606, 0.01834862, 0.        , 0.02752294,
       0.        , 0.93577982, 0.30275229, 1.        , 0.11926606,
       0.00917431, 0.06422018])

In [61]:
YT_category[5]

array([25., 24., 30., 32.,  2.,  0., 30.,  9.,  5., 24.,  2.,  6., 12.,
        5., 14., 20., 61.])

In [68]:
#計算user category，根據他按過的讚的photo 的類別進行計算
YT_NormSum_category

array([[1.09589041e-02, 3.01369863e-02, 8.21917808e-03, ...,
        0.00000000e+00, 5.47945205e-03, 2.73972603e-03],
       [2.23546945e-03, 5.46199702e-01, 1.00000000e+00, ...,
        0.00000000e+00, 7.45156483e-04, 2.98062593e-03],
       [0.00000000e+00, 1.00000000e+00, 6.38297872e-02, ...,
        2.12765957e-02, 0.00000000e+00, 2.12765957e-02],
       ...,
       [1.00000000e+00, 0.00000000e+00, 1.46163216e-02, ...,
        1.21802680e-03, 1.21802680e-02, 3.78806334e-01],
       [9.68054211e-04, 3.87221684e-03, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.93610842e-03],
       [2.08333333e-02, 9.37500000e-02, 6.25000000e-02, ...,
        1.04166667e-02, 1.04166667e-02, 1.04166667e-02]])

In [9]:
YouTuber_bin_category = np.zeros((88,17))
MaxCategory = np.load('../Data/npy/YT_NormMax_category.npy')
for i in range(len(MaxCategory)):
    YouTuber_bin_category[i] = [0 if c < 0.7 else 1 for c in MaxCategory[i]]

In [11]:
YouTuber_bin_category.shape

(88, 17)

In [12]:
np.save('../Data/npy/YouTuber_category_0.7',YouTuber_bin_category)