In [8]:
import os 
import numpy as np
import random
import math
from sklearn.metrics import average_precision_score
import pandas as pd

In [2]:
#從grid_search_weight中找尋不同的file 
path = '../Data/separate_feature/'
files = os.listdir(path)
len(files)
np.load(path+files[0])['U'].shape

(1489, 64)

In [9]:
def square_sum(pars):
    all_squ_sum = []
    for par in pars:
        all_squ_sum.append(np.sum(np.multiply(par,par)))
    return all_squ_sum 
def shape_sum(pars):
    all_shape = []
    for par in pars:
        all_shape.append(par.shape)
    return all_shape
def relu(x):
    return np.maximum(0,x)  

def softmax(x):
    exp_x = np.exp(x)
    softmax_x = exp_x / np.sum(exp_x)
    return softmax_x 

def sigmoid(z):
    return 1 / (1 + np.exp(-z))  

In [10]:
user_following = np.load('../Data/npy/user_following_1489.npy')
all_3374 = np.load('../Data/npy/Image_50_2048D.npy')
user_category = np.load('../Data/npy/user_category_1489.npy')
YouTuber_category = np.load('../Data/npy/YouTuber_category_0.7.npy')
active_users = np.load('../Data/npy/active_userID_1489.npy')
all_3374.shape

(88, 2048)

In [11]:
#over5 = 0
#for num in YouTuber_followers:
#    if num >= 5:
#        over5+=1
#print('The num of followers over 5:',over5)
user_category_norm = np.zeros(user_category.shape)
for i in range(len(user_category)):
    user_category_norm[i] = user_category[i]/np.max(user_category[i])
print('user_category after normalized by max...')
print('user_category_norm shape ',user_category_norm.shape)
following_true = [0]*len(user_following)
for i in range(len(user_following)):
    each_user = []
    for j in range(len(user_following[i])):
        if user_following[i][j] == 1:
            each_user.append(j)
    following_true[i] = each_user
#print(following_true)
#最少跟最多的following 
minlen = 10000
maxlen = 0
num_of_follower = []
for i in range(len(following_true)):
    if len(following_true[i]) < minlen:
        minlen = len(following_true[i])
    if len(following_true[i]) > maxlen:
        maxlen = len(following_true[i])
    num_of_follower.append(len(following_true[i]))
print('Min number of followings ',minlen)
print('Max number of followings ',maxlen)
test_amount = 150
yt_test_amount = 18
user_idx = [i for i in range(len(user_following))]
#user_idx = user_idx_over10
#test_idx is the number of user for testing
random.seed(5)
test_idx = random.sample(user_idx,test_amount)
print(test_idx)
# Training  and Testing --New
train_t = [0]*(len(user_following))
train_f = [0]*(len(user_following))
# Testing 
test_t = [0]*test_amount
test_f = [0]*test_amount
test_pos = -1

for i in range(len(user_following)):
    t_for_train = []
    f_for_train = []
    if i not in test_idx: #if not in test id, just append it to true or false list
        for j in range(88):
            if user_following[i][j] == 1:
                t_for_train.append(j)
            else:
                f_for_train.append(j)
        train_t[i] = t_for_train
        train_f[i] = f_for_train
        
    else: #if in test id, choose 2 true and other 
        test_pos += 1
        temp_t = []
        temp_f = []
        for j in range(88):
            if user_following[i][j] == 1:
                temp_t.append(j)
            else:
                temp_f.append(j)
        #print(len(temp_t),math.ceil(0.5*len(temp_t)))
        t_for_test = random.sample(temp_t,math.ceil(0.5*len(temp_t)))
        f_for_test  = random.sample(temp_f,yt_test_amount-len(t_for_test))
        
        test_t[test_pos] = t_for_test
        test_f[test_pos] = f_for_test
        
        #other for training
        t_for_train = [item for item in temp_t if not item in t_for_test]
        #print(len(t_for_train ))
        f_for_train = [item for item in temp_f if not item in f_for_test]
        train_t[i] = t_for_train
        train_f[i] = f_for_train
total_test = 0
for t in test_t:
    total_test += len(t)
avg = total_test/test_amount
print(avg)

user_category after normalized by max...
user_category_norm shape  (1489, 17)
Min number of followings  5
Max number of followings  34
[1275, 523, 734, 1414, 1335, 1085, 59, 953, 510, 1329, 106, 321, 231, 761, 960, 504, 779, 1113, 208, 1175, 26, 443, 835, 572, 372, 797, 326, 147, 284, 1265, 1264, 911, 259, 270, 3, 10, 428, 441, 339, 340, 592, 642, 407, 1104, 1388, 1281, 419, 403, 784, 611, 44, 739, 849, 298, 540, 133, 679, 617, 1235, 1200, 6, 1220, 1449, 692, 135, 634, 727, 626, 984, 1426, 646, 378, 985, 967, 1443, 360, 116, 524, 46, 732, 827, 37, 1124, 857, 749, 770, 1184, 18, 927, 95, 370, 1277, 402, 243, 503, 946, 705, 1049, 726, 1074, 513, 947, 221, 1207, 752, 605, 75, 886, 186, 426, 697, 1050, 1250, 742, 303, 696, 564, 1438, 1116, 188, 639, 1404, 648, 627, 363, 160, 1283, 304, 1476, 1411, 633, 990, 330, 1474, 99, 165, 1230, 1092, 831, 65, 486, 1216, 704, 512, 933, 1333, 863, 114, 1307, 67]
5.466666666666667


In [12]:
def getScoreMatrix(RS):
    #取出test的資料
    testRS = np.zeros((test_amount,yt_test_amount)) #shape 150*18
    target = np.zeros((test_amount,yt_test_amount))
    #test_t 是true的
    #test_f 是false的

    for z in range(test_amount):
        user_id = test_idx[z]
        #positive target YouTuber list
        youtube_t = test_t[z] 
        #not target YouTuber list
        youtube_f = test_f[z]

        #前兩個放target的RS
        for i in range(len(youtube_t)):
            testRS[z][i] = RS[z][youtube_t[i]]
            target[z][i] = 1
        for i in range(len(youtube_f)):
            testRS[z][i+len(youtube_t)] = RS[z][youtube_f[i]]
    sumtarget = 0
    for i in range(len(target)):
        #print(np.sum(target[i]))
        sumtarget += np.sum(target[i])
    print('num of positive data in testing:',sumtarget)
    print('total testing data:',test_amount*yt_test_amount)
    return target, testRS,sumtarget

def topN(sortlist,n):
    topList = []
    for i in range(n):
        topList.append(sortlist.index(max(sortlist)))
        #print(max(sortlist))
        #print(sortlist.index(max(sortlist)))
        sortlist[sortlist.index(max(sortlist))] = -1000000000
    return topList

def F1_score(prec,rec):
    f1 = (2*prec*rec)/(prec+rec)
    return f1

In [13]:
def getTOP1(target,testRS,sumtarget):
    print('top1')
    correct = 0
    for i in range(len(testRS)):
        top_0 = topN(list(testRS[i]),1) #取一個
        
        #print(top_0)
        if top_0[0] < int(np.sum(target[i])):
            correct += 1
    top1_prec = correct/len(testRS)
    top1_recall = correct/(sumtarget)
    print('prec ',top1_prec,'recall ',top1_recall)
    #f1 score
    print('F1_score:',F1_score(top1_prec,top1_recall))
    return top1_prec,top1_recall,F1_score(top1_prec,top1_recall)
def getTOP3(target,testRS,sumtarget):
    print('top3')
    correct = 0
    for i in range(len(testRS)):
        top_3 = topN(list(testRS[i]),3) #取一個
        
        #print(top_3)
        for j in range(len(top_3)):
            if top_3[j] < int(np.sum(target[i])):
                correct += 1
    top3_prec = correct/(len(testRS)*3)
    top3_recall = correct/(sumtarget)
    print('prec ',top3_prec,'recall ',top3_recall)
    #f1 score
    print('F1_score:',F1_score(top3_prec,top3_recall))
    return top3_prec,top3_recall,F1_score(top3_prec,top3_recall)
def getTOP5(target,testRS,sumtarget):
    print('top5')
    correct = 0
    for i in range(len(testRS)):
        top_5 = topN(list(testRS[i]),5) #取一個
       
        #print(top_5)
        for j in range(len(top_5)):
            if top_5[j] < int(np.sum(target[i])):
                correct += 1
    top5_prec = correct/(len(testRS)*5)
    top5_recall = correct/(sumtarget)
    print('prec ',top5_prec,'recall ',top5_recall)
    #f1 score
    print('F1_score:',F1_score(top5_prec,top5_recall))
    return top5_prec,top5_recall,F1_score(top5_prec,top5_recall)

In [14]:
"""
NDCG
https://daiwk.github.io/posts/nlp-ndcg.html
"""
# pre_list
"""
test_amount = 150
yt_test_amount = 18
"""
def NDCG(target,testRS): #target是真正的喜好
    all_sort = []
    num_ndcg = 10
    pre_matrix = np.zeros(shape=(test_amount,yt_test_amount)) #(150,18)
    for i in range(test_amount): #user amount = 150
        top_n = topN(list(testRS[i]),num_ndcg) #取10個
        #print(top_n)
        all_sort.append(topN(list(testRS[i]),len(testRS[i])))
        #print('all_sort',topN(list(testRS[i]),len(testRS[i])))
        for j in range(len(top_n)):
            pre_matrix[i][top_n[j]] = 1

    #Ideal DCG，理想状况下的DCG。也就是说，相关性完全由高到低排序时算出的DCG：
    def IDCG(ideal_list): #ideal_list example = [1,1,1,1,1,0,0,....]
        idcg=0
        print('ideal',ideal_list)
        for i in range(len(ideal_list)):
            #print((2**true_list[i]-1),math.log2(i+2))
            idcg+= (2**ideal_list[i]-1)/ math.log2(i+2)
        #print('idcg',idcg)
        return idcg
    def DCG(prec_list): #找出前n名的[1,1,1,0,...]
        dcg=0
        print('prec',prec_list)
        for i in range(len(prec_list)):
            dcg+= (2**prec_list[i]-1)/ math.log2(i+2)
        #print('dcg',dcg)
        return dcg
    total_ndcg = 0
    
    for m in range(test_amount): # the number of testing users
        idcg = IDCG(target[m][:num_ndcg])
        pre_list = []
        least_pre_list = []
        for s in all_sort[m][:num_ndcg]:
            #print(m,s,target[m][s])
            pre_list.append(target[m][s]) #把prec_list 的 score加進去
        for s in all_sort[m][num_ndcg:]:
            #print(s)
            #print(target[m][s])
            least_pre_list.append(target[m][s]) #把prec_list 的 score加進去
        dcg = DCG(pre_list)
        ndcg = dcg/idcg
        #print(ndcg)
        total_ndcg += ndcg
    avg_ndcg = total_ndcg/test_amount
    print('NDCG:',avg_ndcg)
    return pre_matrix,avg_ndcg

# MAP
"""
>>> y_true = np.array([0, 0, 1, 1])
>>> y_scores = np.array([0.1, 0.4, 0.35, 0.8])
>>> average_precision_score(y_true, y_scores)
"""
def MAP(target,pre_matrix):
    print('target:',target)
    print('predict:',pre_matrix)
    total_prec = 0
    for u in range(test_amount):
        y_true = target[u]
        y_scores = pre_matrix[u]
        total_prec+=average_precision_score(y_true, y_scores)
    Map_value = total_prec/test_amount
    print('MAP',Map_value)
    return Map_value

In [15]:
def testing(U, Y, A, E,Au, Ay, Aa, Av,B):
    """
    print('U shape',U.shape)
    print('Y shape',Y.shape)
    print('A shape',A.shape)
    print('E shape',E.shape)
    print('Wv shape',Av.shape)
    print(np.max(Au))
    print(np.max(Ay))
    print(np.max(Aa))
    print(np.max(Av))
    print(np.max(B))
    """
    if E.shape[1] == 2048:
        all_3374 = np.load('../Data/npy/Image_50_2048D.npy')
    elif E.shape[1] == 512:
        all_3374 = np.load('../Data/npy/Video_512D_6650.npy')
    elif E.shape[1] == 600:
        all_3374 = np.load('../Data/npy/Text_600D.npy')
    elif E.shape[1] == 2939:
        all_3374 = np.load('../Data/npy/all_2939D_img0.5.npy')
    elif E.shape[1] == 3239-64:
        all_3374 = np.load('../Data/npy/mask_feature/no_following.npy')
    elif E.shape[1] == 3239-15:
        all_3374 = np.load('../Data/npy/mask_feature/no_social.npy')
    elif E.shape[1] == 3239-2048:
        all_3374 = np.load('../Data/npy/mask_feature/no_image.npy')
    elif E.shape[1] == 3239-512:
        all_3374 = np.load('../Data/npy/mask_feature/no_video.npy')
    #elif E.shape[1] == 3239-600:
    #    all_3374 = np.load('../Data/npy/mask_feature/no_text.npy')
    elif E.shape[1] == 2939-300:
        all_3374 = np.load('../Data/npy/mask_feature/no_300text.npy')
    elif E.shape[1] == 2939-512:
        all_3374 = np.load('../Data/npy/mask_feature/no_300video.npy')
    elif E.shape[1] == 2939-15:
        all_3374 = np.load('../Data/npy/mask_feature/no_300social.npy')
    elif E.shape[1] == 2939-64:
        all_3374 = np.load('../Data/npy/mask_feature/no_300following.npy')
    elif E.shape[1] == 2939-2048:
        all_3374 = np.load('../Data/npy/mask_feature/no_300image.npy')
    test_amount = 150
    yt_test_amount = 18
    result=np.zeros((test_amount,88))
    RS=np.zeros((test_amount,88))
    #test_idx --> Test 的 index
    sum_alpha = 0
    for s in range(test_amount):
        #print(s,test_idx[s])

        yes=[]
        #sample=random.sample(train_t[test_idx[s]],len(train_t[test_idx[s]])) #從training part 的positive feedback 取出YouTuber 當成Auxilary
        sample = train_t[test_idx[s]]
        #sample=result_yes_id[now]
        alpha=np.zeros([len(sample)])

        for a in range(len(sample)):
            r =np.max(YouTuber_category[sample[a]]*user_category_norm[test_idx[s]]) #sample a 的category vec *user_category vec
            alpha_a = np.dot(Au[test_idx[s]][sample[a]],np.expand_dims(U[test_idx[s]],0).T)+np.dot(Ay[test_idx[s]][sample[a]],np.expand_dims(Y[sample[a]],0).T)+np.dot(Aa[test_idx[s]][sample[a]],
                    np.expand_dims(A[sample[a]],0).T)+ np.dot(Av[test_idx[s]][sample[a]],np.dot(E,np.expand_dims(all_3374[sample[a]],0).T))
            """
            relu part ...
            """
            alpha[a]=np.sum((relu(alpha_a)))*r
            """
            tanh part ...
            """
            #alpha[a]=np.sum((np.tanh(alpha_a)))*r
            
            
        mul=np.zeros((1,64))
        #print('alpha--------',alpha)
        #print('add alpha------------',np.add(alpha,0.000000001))
        added_alpha = np.add(alpha,0.0000000001)
        norm_alpha = added_alpha/np.sum(added_alpha)
        #print('alpha-----------',alpha)
        #print('norm alpha--------------',norm_alpha)
        sum_alpha += np.sum(alpha)
        for i in range(len(sample)):
            mul+=norm_alpha[i]*A[sample[i]] #attention alpha*Ai part
        new_mul=mul+U[test_idx[s]]  #(U+auxilary)
    
        
        
        for k in range(88):
            result[s][k]=np.dot(new_mul,Y[k].T) #(U+auxilary)*photo latent factor
            RS[s][k] = np.dot(new_mul,Y[k].T)+np.dot(B[test_idx[s]],np.dot(E, all_3374[k].T))
            """
            print('================================')
            print('U',np.sum(U[test_idx[s]] ))
            print('A',np.sum(mul))
            print('Y',np.sum(Y[k]))
            print('B',np.sum(B[test_idx[s]]))
            print('E',np.sum(np.dot(E, all_3374[k].T)))
            print('User',np.dot(U[test_idx[s]],Y[k].T))
            print('Aux',np.dot(mul,Y[k].T))
            print('Former',np.dot(new_mul,Y[k].T))
            print('Later',np.dot(B[test_idx[s]],np.dot(E, all_3374[k].T)))
            print('RS',np.dot(new_mul,Y[k].T)+np.dot(B[test_idx[s]],np.dot(E, all_3374[k].T)))
            print('--------------------------------')
            """
            
    print('sum_alpha',sum_alpha)
    return RS

In [19]:
#With Embedding
import os 
#從grid_search_weight中找尋不同的file 
path = '../Data/grid_search_weight/vbpr/'
all_files = os.listdir(path)
print(all_files)

['vbpr_onlyImg.npz', 'vbpt_ImgVideo.npz']


In [21]:
par_files = list(set([file.split('_Edims')[0] for file in all_files]))
print(par_files)
for par_file in par_files:
    NDCG_List = []
    MAP_List = []
    DIM_List = []
    TOP1_Prec = []
    TOP3_Prec = []
    TOP5_Prec = []
    TOP1_F1 = []
    TOP3_F1 = []
    TOP5_F1 = []
    TOP1_Recall = []
    TOP3_Recall = []
    TOP5_Recall = []
    
    csv_path = '../Data/grid_search_weight/CSV_Tan/'
    for file in all_files:
        if par_file in file:
            print(file)
            par_data = np.load(path+file)
            U = par_data['U']
            Y = par_data['Y']
            A = par_data['A']
            E = par_data['E']
            #W1 = par_data['W1']
            Wu = par_data['Wu']
            Wy = par_data['Wy']
            Wa = par_data['Wa']
            Wv = par_data['Wv']
            B = par_data['B']
            RS = testing(U, Y, A, E,Wu, Wy, Wa, Wv,B)
            target,testRS,sumtarget = getScoreMatrix(RS)
            prec_1,recall_1,f1_1 = getTOP1(target,testRS,sumtarget)
            prec_3,recall_3,f1_3 = getTOP3(target,testRS,sumtarget)
            prec_5,recall_5,f1_5 = getTOP5(target,testRS,sumtarget)
            pre_matrix,avg_ndcg = NDCG(target,testRS)
            Map_value = MAP(target,pre_matrix)
            NDCG_List.append(avg_ndcg)
            MAP_List.append(Map_value)
            DIM_List.append(file.split('Edims')[1].split('.npz')[0])
            TOP1_Prec.append(prec_1)
            TOP1_Recall.append(recall_1)
            TOP1_F1.append(f1_1)
            TOP3_Prec.append(prec_3)
            TOP3_Recall.append(recall_3)
            TOP3_F1.append(f1_3)
            TOP5_Prec.append(prec_5)
            TOP5_Recall.append(recall_5)
            TOP5_F1.append(f1_5)
            print('--------------------------------------------------------------------------------------------')
    #print(NDCG_List)
    #print(DIM_List)
    result_dict = {'Dims':DIM_List,'NDCG':NDCG_List,'MAP':MAP_List,
                   'TOP1 Precision':TOP1_Prec,'TOP1 Recall':TOP1_Recall,'TOP1 F1':TOP1_F1,
                  'TOP3 Precision':TOP3_Prec,'TOP3 Recall':TOP3_Recall,'TOP3 F1':TOP3_F1,
                  'TOP5 Precision':TOP5_Prec,'TOP5 Recall':TOP5_Recall,'TOP5 F1':TOP5_F1}
    df = pd.DataFrame(result_dict)
    df.to_csv(csv_path+par_file+'.csv',index=False)

['Img0.5_Video_E200.npz']
Img0.5_Video_E200.npz
sum_alpha 0.20550421874716984
num of positive data in testing: 820.0
total testing data: 2700
top1
prec  0.6133333333333333 recall  0.11219512195121951
F1_score: 0.18969072164948456
top3
prec  0.5622222222222222 recall  0.30853658536585366
F1_score: 0.3984251968503936
top5
prec  0.576 recall  0.526829268292683
F1_score: 0.5503184713375795
all_sort [0, 4, 8, 13, 2, 10, 3, 14, 15, 9, 1, 5, 7, 6, 16, 12, 17, 11]
all_sort [1, 0, 2, 4, 11, 6, 8, 5, 3, 14, 17, 10, 7, 13, 15, 9, 16, 12]
all_sort [2, 1, 3, 4, 5, 12, 8, 10, 13, 16, 0, 14, 15, 9, 6, 17, 7, 11]
all_sort [5, 6, 11, 16, 14, 17, 10, 9, 7, 12, 1, 4, 13, 15, 2, 0, 3, 8]
all_sort [8, 7, 15, 14, 3, 5, 1, 13, 11, 4, 2, 0, 16, 17, 6, 12, 10, 9]
all_sort [1, 10, 17, 5, 0, 4, 13, 3, 2, 11, 16, 9, 6, 7, 15, 14, 8, 12]
all_sort [2, 6, 5, 17, 9, 7, 15, 11, 16, 8, 14, 10, 12, 3, 13, 4, 0, 1]
all_sort [14, 0, 2, 4, 5, 7, 1, 15, 3, 13, 6, 9, 11, 16, 8, 12, 17, 10]
all_sort [13, 2, 3, 1, 11, 0, 9, 5,

56 5 1.0
56 8 0.0
56 3 1.0
56 4 1.0
56 2 1.0
56 17 0.0
56 13 0.0
56 0 1.0
56 9 0.0
prec [1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0]
ideal [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
57 0 1.0
57 1 1.0
57 11 0.0
57 2 1.0
57 15 0.0
57 8 0.0
57 12 0.0
57 17 0.0
57 13 0.0
57 6 0.0
prec [1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
58 11 0.0
58 2 1.0
58 15 0.0
58 0 1.0
58 1 1.0
58 16 0.0
58 10 0.0
58 12 0.0
58 17 0.0
58 7 0.0
prec [0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
59 0 1.0
59 17 0.0
59 5 1.0
59 2 1.0
59 8 1.0
59 1 1.0
59 4 1.0
59 9 1.0
59 11 0.0
59 13 0.0
prec [1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
60 0 1.0
60 7 0.0
60 2 1.0
60 13 0.0
60 4 1.0
60 17 0.0
60 16 0.0
60 1 1.0
60 11 0.0
60 10 0.0
prec [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0]
ideal [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
61 1 1.0
61 2 1.0
61 15 0.0
61 6 0.0
61 0 1.0
61 12 0.0
61 7 0.0
61 

144 11 0.0
144 8 0.0
144 16 0.0
144 4 0.0
144 6 0.0
144 2 1.0
144 15 0.0
prec [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
145 6 1.0
145 1 1.0
145 4 1.0
145 10 0.0
145 2 1.0
145 0 1.0
145 3 1.0
145 5 1.0
145 14 0.0
145 15 0.0
prec [1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
146 10 0.0
146 4 0.0
146 5 0.0
146 14 0.0
146 16 0.0
146 7 0.0
146 0 1.0
146 3 1.0
146 13 0.0
146 2 1.0
prec [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0]
ideal [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
147 2 1.0
147 5 0.0
147 1 1.0
147 0 1.0
147 15 0.0
147 3 1.0
147 10 0.0
147 12 0.0
147 14 0.0
147 7 0.0
prec [1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
148 0 1.0
148 7 0.0
148 9 0.0
148 5 0.0
148 2 1.0
148 12 0.0
148 1 1.0
148 3 1.0
148 4 0.0
148 15 0.0
prec [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
149 2 1.0
149 4 1.0
149 17 0.0
149 1 1.0
149

IndexError: list index out of range

# Separate Feature Observation

In [20]:
#With Embedding
import os 
#從grid_search_weight中找尋不同的file 
path = '../Data/npy/mask_feature/result300/'
all_files = os.listdir(path)
print(all_files)

['Img0.5_no_300following_E200.npz', 'Img0.5_no_300image_E200.npz', 'Img0.5_no_300social_E200.npz', 'Img0.5_no_300text_E200.npz', 'Img0.5_no_300video_E200.npz']


In [21]:
par_files = list(set([file.split('_')[1]+'_'+file.split('_')[2] for file in all_files]))
print(par_files)
for par_file in par_files:
    NDCG_List = []
    MAP_List = []
    DIM_List = []
    TOP1_Prec = []
    TOP3_Prec = []
    TOP5_Prec = []
    TOP1_F1 = []
    TOP3_F1 = []
    TOP5_F1 = []
    TOP1_Recall = []
    TOP3_Recall = []
    TOP5_Recall = []
    
    #csv_path = '../Data/grid_search_weight/CSV_Tan/'
    csv_path = '../Data/npy/mask_feature/csv/'
    for file in all_files:
        if par_file in file:
            print(file)
            par_data = np.load(path+file)
            U = par_data['U']
            Y = par_data['Y']
            A = par_data['A']
            E = par_data['E']
            #W1 = par_data['W1']
            Wu = par_data['Wu']
            Wy = par_data['Wy']
            Wa = par_data['Wa']
            Wv = par_data['Wv']
            B = par_data['B']
            RS = testing(U, Y, A, E,Wu, Wy, Wa, Wv,B)
            target,testRS,sumtarget = getScoreMatrix(RS)
            print('target',target)
            prec_1,recall_1,f1_1 = getTOP1(target,testRS,sumtarget)
            prec_3,recall_3,f1_3 = getTOP3(target,testRS,sumtarget)
            prec_5,recall_5,f1_5 = getTOP5(target,testRS,sumtarget)
            pre_matrix,avg_ndcg = NDCG(target,testRS)
            Map_value = MAP(target,pre_matrix)
            NDCG_List.append(avg_ndcg)
            MAP_List.append(Map_value)
            DIM_List.append(file.split('_')[1])
            TOP1_Prec.append(prec_1)
            TOP1_Recall.append(recall_1)
            TOP1_F1.append(f1_1)
            TOP3_Prec.append(prec_3)
            TOP3_Recall.append(recall_3)
            TOP3_F1.append(f1_3)
            TOP5_Prec.append(prec_5)
            TOP5_Recall.append(recall_5)
            TOP5_F1.append(f1_5)
            print('--------------------------------------------------------------------------------------------')
    #print(NDCG_List)
    #print(DIM_List)
    result_dict = {'Dims':DIM_List,'NDCG':NDCG_List,'MAP':MAP_List,
                   'TOP1 Precision':TOP1_Prec,'TOP1 Recall':TOP1_Recall,'TOP1 F1':TOP1_F1,
                  'TOP3 Precision':TOP3_Prec,'TOP3 Recall':TOP3_Recall,'TOP3 F1':TOP3_F1,
                  'TOP5 Precision':TOP5_Prec,'TOP5 Recall':TOP5_Recall,'TOP5 F1':TOP5_F1}
    df = pd.DataFrame(result_dict)
    df.to_csv(csv_path+par_file+'.csv',index=False)

['no_300text', 'no_300video', 'no_300image', 'no_300social', 'no_300following']
Img0.5_no_300text_E200.npz
sum_alpha 0.2572009457758803
num of positive data in testing: 820.0
total testing data: 2700
target [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
top1
prec  0.6333333333333333 recall  0.11585365853658537
F1_score: 0.19587628865979384
top3
prec  0.5911111111111111 recall  0.32439024390243903
F1_score: 0.41889763779527556
top5
prec  0.5826666666666667 recall  0.5329268292682927
F1_score: 0.556687898089172
ideal [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
prec [0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0]


sum_alpha 0.2941435327991859
num of positive data in testing: 820.0
total testing data: 2700
target [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
top1
prec  0.6 recall  0.10975609756097561
F1_score: 0.18556701030927836
top3
prec  0.6044444444444445 recall  0.33170731707317075
F1_score: 0.42834645669291344
top5
prec  0.5706666666666667 recall  0.5219512195121951
F1_score: 0.5452229299363057
ideal [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
prec [1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 0.

sum_alpha 0.23150336465723698
num of positive data in testing: 820.0
total testing data: 2700
target [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
top1
prec  0.6666666666666666 recall  0.12195121951219512
F1_score: 0.2061855670103093
top3
prec  0.6 recall  0.32926829268292684
F1_score: 0.4251968503937008
top5
prec  0.5733333333333334 recall  0.524390243902439
F1_score: 0.5477707006369428
ideal [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
prec [1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0

Img0.5_no_300social_E200.npz
sum_alpha 0.3078268131513102
num of positive data in testing: 820.0
total testing data: 2700
target [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
top1
prec  0.6 recall  0.10975609756097561
F1_score: 0.18556701030927836
top3
prec  0.6222222222222222 recall  0.34146341463414637
F1_score: 0.4409448818897638
top5
prec  0.5706666666666667 recall  0.5219512195121951
F1_score: 0.5452229299363057
ideal [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
prec [1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0]

sum_alpha 0.2748173423568841
num of positive data in testing: 820.0
total testing data: 2700
target [[1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]]
top1
prec  0.5933333333333334 recall  0.10853658536585366
F1_score: 0.18350515463917527
top3
prec  0.5911111111111111 recall  0.32439024390243903
F1_score: 0.41889763779527556
top5
prec  0.5853333333333334 recall  0.5353658536585366
F1_score: 0.5592356687898089
ideal [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
prec [1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
ideal [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
prec [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]
ideal [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
prec [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0]
ideal [1. 1.

In [20]:
#For VBPR
par_files = list(set([file.split('_')[1] for file in all_files]))
print(par_files)
for par_file in par_files:
    NDCG_List = []
    MAP_List = []
    DIM_List = []
    TOP1_Prec = []
    TOP3_Prec = []
    TOP5_Prec = []
    TOP1_F1 = []
    TOP3_F1 = []
    TOP5_F1 = []
    TOP1_Recall = []
    TOP3_Recall = []
    TOP5_Recall = []
    
    csv_path = '../Data/grid_search_weight/CSV_Tan/'
    #csv_path = '../Data/npy/mask_feature/csv/'
    for file in all_files:
        if par_file in file:
            print(file)
            par_data = np.load(path+file)
            U = par_data['U']
            Y = par_data['Y']
            A = par_data['A']
            E = par_data['E']
            #W1 = par_data['W1']
            Wu = par_data['Wu']
            Wy = par_data['Wy']
            Wa = par_data['Wa']
            Wv = par_data['Wv']
            B = par_data['B']
            RS = testing(U, Y, A, E,Wu, Wy, Wa, Wv,B)
            target,testRS,sumtarget = getScoreMatrix(RS)
            print('target',target)
            prec_1,recall_1,f1_1 = getTOP1(target,testRS,sumtarget)
            prec_3,recall_3,f1_3 = getTOP3(target,testRS,sumtarget)
            prec_5,recall_5,f1_5 = getTOP5(target,testRS,sumtarget)
            pre_matrix,avg_ndcg = NDCG(target,testRS)
            Map_value = MAP(target,pre_matrix)
            NDCG_List.append(avg_ndcg)
            MAP_List.append(Map_value)
            DIM_List.append(file.split('_')[1])
            TOP1_Prec.append(prec_1)
            TOP1_Recall.append(recall_1)
            TOP1_F1.append(f1_1)
            TOP3_Prec.append(prec_3)
            TOP3_Recall.append(recall_3)
            TOP3_F1.append(f1_3)
            TOP5_Prec.append(prec_5)
            TOP5_Recall.append(recall_5)
            TOP5_F1.append(f1_5)
            print('--------------------------------------------------------------------------------------------')
    #print(NDCG_List)
    #print(DIM_List)
    result_dict = {'Dims':DIM_List,'NDCG':NDCG_List,'MAP':MAP_List,
                   'TOP1 Precision':TOP1_Prec,'TOP1 Recall':TOP1_Recall,'TOP1 F1':TOP1_F1,
                  'TOP3 Precision':TOP3_Prec,'TOP3 Recall':TOP3_Recall,'TOP3 F1':TOP3_F1,
                  'TOP5 Precision':TOP5_Prec,'TOP5 Recall':TOP5_Recall,'TOP5 F1':TOP5_F1}
    df = pd.DataFrame(result_dict)
    df.to_csv(csv_path+par_file+'.csv',index=False)

['onlyImg.npz', 'ImgVideo.npz']
vbpr_onlyImg.npz


KeyError: 'A is not a file in the archive'

# NDCG For Different Dimensions

In [111]:
######## code here !!!!

(10, 20)

In [69]:
def topN(sortlist,n):
    topList = []
    for i in range(n):
        topList.append(sortlist.index(max(sortlist)))
        #print(max(sortlist))
        #print(sortlist.index(max(sortlist)))
        sortlist[sortlist.index(max(sortlist))] = -1000000000
    return topList

In [70]:
count_0_all = []
for i in range(len(testRS)):
    top_0 = topN(list(testRS[i]),int(np.sum(target[i])))
    count_0_all.append(top_0)
    print(top_0)

acc_0 = 0
total = 0
for i in range(len(count_0_all)):
    for j in range(len(count_0_all[i])):
        #print(int(np.sum(target[i])))
        total+=int(np.sum(target[i]))
        if count_0_all[i][j] < int(np.sum(target[i])): #代表是0或1 (也就是target)
            acc_0 += 1
avg_acc = acc_0/100
print('avg_accuarcy for count_0:',avg_acc)
print(acc_0)

[0, 2, 1]
[3, 6, 2]
[1, 2, 13, 4, 5, 3, 17]
[1, 10, 8, 2, 5, 4]
[4, 1, 12]
[1, 15, 11]
[2, 1, 10, 0]
[3, 2, 5, 7, 4, 18]
[3, 18, 8, 5, 13]
[12, 16, 7, 0, 9]
avg_accuarcy for count_0: 0.24
24


# TOP1,TOP3,TOP5

In [71]:
def F1_score(prec,rec):
    f1 = (2*prec*rec)/(prec+rec)
    return f1

# NDCG 

In [172]:
a_list = [0.02162337, 0.02162659, 0.00240219, 0.00780985, 0.02162318, 0.00780592, 0.00780849]
softmax(a_list)

array([0.14409628, 0.14409674, 0.14135303, 0.14211949, 0.14409625,
       0.14211893, 0.14211929])

In [7]:

user = []
for i in range(3):
    temp_t = []
    temp_t.append(1)
    temp_t.append(2)
    temp_t.append(3)
    user.append(temp_t)
np.array(user)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])