In [17]:
import os 
import numpy as np
import random
import math

In [10]:
#從grid_search_weight中找尋不同的file 
path = '../Data/grid_search_weight/0106/'
files = os.listdir(path)
len(files)

1

In [21]:
def square_sum(pars):
    all_squ_sum = []
    for par in pars:
        all_squ_sum.append(np.sum(np.multiply(par,par)))
    return all_squ_sum 
def shape_sum(pars):
    all_shape = []
    for par in pars:
        all_shape.append(par.shape)
    return all_shape
def relu(x):
    return np.maximum(0,x)  

def softmax(x):
    exp_x = np.exp(x)
    softmax_x = exp_x / np.sum(exp_x)
    return softmax_x 

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [12]:
for file in files:
    par_data = np.load(path+file)
    print(file)
    U = par_data['U']
    Y = par_data['Y']
    A = par_data['A']
    E = par_data['E']
    W1 = par_data['W1']
    Wu = par_data['Wu']
    Wy = par_data['Wy']
    Wa = par_data['Wa']
    Wv = par_data['Wv']
    B = par_data['B']
    all_result = square_sum([U,Y,A,E,W1,Wu,Wy,Wa,Wv,B])
    all_shape = shape_sum([U,Y,A,E,W1,Wu,Wy,Wa,Wv,B])
    print('[U,Y,A,E,W1,Wu,Wy,Wa,Wv,B]')
    print(all_shape)
    print(all_result)
    print('U:',U)
    print('Y:',Y)
    #print(W1)
    print('UY:',np.sum(np.multiply(U[1],Y[1])))
    print('AY:',np.sum(np.multiply(A[1],Y[1])))
    print('WuU:',np.sum(np.multiply(Wu[1],U[1])))
    print('WyY:',np.sum(np.multiply(Wy[1],Y[1])))
    print('WaA:',np.sum(np.multiply(Wa[1],A[1])))
    #print('WvV:',np.sum(np.multiply(W1[1],U[1])))
    print('--------------------------------------------------------------------------------')

0.01_0.01_1_1.npz
[U,Y,A,E,W1,Wu,Wy,Wa,Wv,B]
[(100, 128), (88, 128), (88, 128), (150, 3374), (100, 128), (100, 128, 128), (88, 128, 128), (88, 128, 128), (88, 128, 3374), (100, 150)]
[0.0058118636, 5388.1426, 112.074615, 2.860661e-08, 5.847447e-06, 0.0007583066, 28.021545, 28.021769, 64.6911, 0.43638396]
U: [[-5.32647668e-22 -1.09818226e-23  2.12001188e-27 ... -1.15999409e-23
   3.26142000e-26 -1.19329387e-26]
 [ 1.47269229e-21  1.19449974e-32  1.18967702e-30 ... -3.21934451e-24
  -2.76593901e-24 -7.99697607e-22]
 [-2.15751748e-28 -3.27366337e-31 -1.54802826e-31 ...  5.78859310e-31
  -4.17782541e-31 -3.39101720e-31]
 ...
 [-3.86073064e-31 -1.34038612e-31 -4.61846840e-31 ...  1.08680095e-31
   2.84326599e-31 -4.11557123e-31]
 [-4.94142560e-31  5.03256591e-31 -3.34116872e-32 ... -5.85282023e-31
   1.50598882e-31  2.74783842e-31]
 [-8.09086251e-28  1.62903919e-30 -4.17564338e-28 ...  2.97350764e-26
  -3.22715081e-28 -1.50828727e-20]]
Y: [[-0.4679325  -0.41084346  0.80363816 ... -0.5206709

In [56]:
print(np.sum(U))
print(np.sum(Y))

-0.023778245
90.54772


In [18]:
user_following = np.load('../Data/npy/user_following_1489.npy')[:100]
all_3374 = np.load('../Data/npy/all_3374D.npy')
user_category = np.load('../Data/npy/user_category_1489.npy')[:100]
YouTuber_category = np.load('../Data/npy/YouTuber_category_0.7.npy')
active_users = np.load('../Data/npy/active_userID_1489.npy')[:100]
#The number of followers for each YouTuber
YouTuber_followers = np.sum(user_following, axis=0)
print(YouTuber_followers)
over5 = 0
for num in YouTuber_followers:
    if num >= 5:
        over5+=1
print('The num of followers over 5:',over5)
user_category_norm = np.zeros(user_category.shape)
for i in range(len(user_category)):
    user_category_norm[i] = user_category[i]/np.max(user_category[i])
print('user_category after normalized by max...')
print('user_category_norm shape ',user_category_norm.shape)
following_true = [0]*len(user_following)
for i in range(len(user_following)):
    each_user = []
    for j in range(len(user_following[i])):
        if user_following[i][j] == 1:
            each_user.append(j)
    following_true[i] = each_user
#print(following_true)
#最少跟最多的following 
minlen = 10000
maxlen = 0
num_of_follower = []
for i in range(len(following_true)):
    if len(following_true[i]) < minlen:
        minlen = len(following_true[i])
    if len(following_true[i]) > maxlen:
        maxlen = len(following_true[i])
    num_of_follower.append(len(following_true[i]))
print('Min number of followings ',minlen)
print('Max number of followings ',maxlen)
test_amount = 10
yt_test_amount = 20
user_idx = [i for i in range(len(user_following))]
#user_idx = user_idx_over10
#test_idx is the number of user for testing
random.seed(3)
test_idx = random.sample(user_idx,test_amount)
# Training  and Testing --New
train_t = [0]*(len(user_following))
train_f = [0]*(len(user_following))
# Testing 
test_t = [0]*test_amount
test_f = [0]*test_amount
test_pos = -1

for i in range(len(user_following)):
    t_for_train = []
    f_for_train = []
    if i not in test_idx: #if not in test id, just append it to true or false list
        for j in range(88):
            if user_following[i][j] == 1:
                t_for_train.append(j)
            else:
                f_for_train.append(j)
        train_t[i] = t_for_train
        train_f[i] = f_for_train
        
    else: #if in test id, choose 2 true and other 
        test_pos += 1
        temp_t = []
        temp_f = []
        for j in range(88):
            if user_following[i][j] == 1:
                temp_t.append(j)
            else:
                temp_f.append(j)
        #print(len(temp_t),math.ceil(0.5*len(temp_t)))
        t_for_test = random.sample(temp_t,math.ceil(0.5*len(temp_t)))
        f_for_test  = random.sample(temp_f,yt_test_amount-len(t_for_test))
        
        test_t[test_pos] = t_for_test
        test_f[test_pos] = f_for_test
        
        #other for training
        t_for_train = [item for item in temp_t if not item in t_for_test]
        #print(len(t_for_train ))
        f_for_train = [item for item in temp_f if not item in f_for_test]
        train_t[i] = t_for_train
        train_f[i] = f_for_train
total_test = 0
for t in test_t:
    total_test += len(t)
avg = total_test/test_amount
print(avg)

[ 8  0  2 24  1  0  0 11 47  7 25 32 10  1 16  1  6 24  3  2  1  6  4  0
 39 39 10 16 27 22  0  2 17 15  0  2  0  8  2  1 28 16  3 33  9 24  0  3
  0  9  0  0  0  2 28  2  2 18  0  3 23  0  2 39  0  1  1 65  0  2 18 21
  7  1 47 14 19  1  3 66  3  0 28  3 20  0  6  0]
The num of followers over 5: 42
user_category after normalized by max...
user_category_norm shape  (100, 17)
Min number of followings  5
Max number of followings  21
4.5


In [42]:
def testing(U, Y, A, E, A1, Au, Ay, Aa, Av,B):
    #print(A1)
    result=np.zeros((test_amount,88))
    RS=np.zeros((test_amount,88))
    #test_idx --> Test 的 index
    max1 = 0
    maxu = 0
    maxy = 0
    maxa = 0
    maxv = 0
    min1 = 100000000000000000
    minu = 100000000000000000
    miny = 100000000000000000
    mina = 100000000000000000
    minv = 100000000000000000
    test_yes_id=[]
    for s in range(test_amount):
        print(s,test_idx[s])

        yes=[]
        sample=random.sample(train_t[test_idx[s]],len(train_t[test_idx[s]])) #從training part 的positive feedback 取出YouTuber 當成Auxilary
        #sample=result_yes_id[now]
        test_yes_id.append(sample)
        alpha=np.zeros([len(sample)])

        for a in range(len(sample)):
            r =np.max(YouTuber_category[sample[a]]*user_category_norm[test_idx[s]]) #sample a 的category vec *user_category vec
            #print(test_idx[s])
            #print(np.dot(Au[test_idx[s]],np.expand_dims(U[test_idx[s]],0)))

            #Observe each part in attention , below par are all (128,1)
            testW1 = np.sum(A1[test_idx[s]])
            #print(A1[test_idx[s]])
            WuUu = np.sum(np.dot(Au[test_idx[s]],np.expand_dims(U[test_idx[s]],0).T))
            WyYy = np.sum(np.dot(Ay[sample[a]],np.expand_dims(Y[sample[a]],0).T))
            WaAa = np.sum(np.dot(Aa[test_idx[s]],np.expand_dims(A[sample[a]],0).T))
            WvVy = np.sum(np.dot(Av[test_idx[s]],np.expand_dims(all_3374[sample[a]],0).T))
            print('The sum of each par -->\nw1:',testW1,'\nWuU:',WuUu,'\nwyY:',WyYy,'\nWaA:',WaAa,'\nWvV:',WvVy)
            if testW1 > max1:
                max1 = testW1
            if testW1 < min1:
                min1 = testW1
            if WuUu > maxu:
                maxu = WuUu
            if WuUu < minu:
                minu = WuUu
            if WyYy > maxy:
                maxy = WyYy
            if WyYy < miny:
                miny = WyYy
            if WaAa > maxa:
                maxa = WaAa
            if WaAa < mina:
                mina = WaAa
            if WvVy > maxv:
                mxv = WvVy
            if WvVy < minv:
                minv = WvVy
            #Have w1
            alpha[a]=np.dot(A1[test_idx[s]],(relu(np.dot(Au[test_idx[s]],np.expand_dims(U[test_idx[s]],0).T)+np.dot(Ay[sample[a]],np.expand_dims(Y[sample[a]],0).T)+np.dot(Aa[test_idx[s]],
                                np.expand_dims(A[sample[a]],0).T)+ np.dot(Av[test_idx[s]],np.expand_dims(all_3374[sample[a]],0).T))))*r
            #Without w1
            #alpha[a]=np.sum((relu(np.dot(Au[test_idx[s]],np.expand_dims(U[test_idx[s]],0).T)+np.dot(Ay[sample[a]],np.expand_dims(Y[sample[a]],0).T)+np.dot(Aa[test_idx[s]],
            #                    np.expand_dims(A[sample[a]],0).T)+ np.dot(Av[test_idx[s]],np.expand_dims(all_3374[sample[a]],0).T))))*r
        mul=np.zeros((1,128))
        print('alpha------------',alpha)
        print('softmax alpha--------------',softmax(alpha))
        for i in range(len(sample)):
            mul+=softmax(alpha)[i]*A[sample[i]] #attention alpha*Ai part 
        new_mul=mul+U[test_idx[s]]  #(U+auxilary)
        for k in range(88):
            result[s][k]=np.dot(new_mul,Y[k].T) #(U+auxilary)*photo latent factor
            RS[s][k] = np.dot(new_mul,Y[k].T)+np.dot(B[test_idx[s]],np.dot(E, all_3374[k].T))
    #print(max1,maxu,maxy,maxa,maxv)
    #print(min1,minu,miny,mina,minv)
    return RS

In [43]:
import os 
#從grid_search_weight中找尋不同的file 
path = '../Data/grid_search_weight/0106/'
files = os.listdir(path)
#U, Y, A, E, A1, Au, Ay, Aa, Av,B =sess.run([user_latent, item_latent, aux_item, embedding, W1, Wu, Wy, Wa, Wv,Beta])
for file in files:
    par_data = np.load(path+file)
    U = par_data['U']
    Y = par_data['Y']
    A = par_data['A']
    E = par_data['E']
    W1 = par_data['W1']
    Wu = par_data['Wu']
    Wy = par_data['Wy']
    Wa = par_data['Wa']
    Wv = par_data['Wv']
    B = par_data['B']
    RS = testing(U, Y, A, E, W1, Wu, Wy, Wa, Wv,B)

0 30
The sum of each par -->
w1: -1.1512744e-05 
WuU: 1.1890783e-19 
wyY: 0.05912169 
WaA: -0.22204512 
WvV: -0.6340856108393846
The sum of each par -->
w1: -1.1512744e-05 
WuU: 1.1890783e-19 
wyY: -0.0031648949 
WaA: -0.2889682 
WvV: -0.45657874034508406
The sum of each par -->
w1: -1.1512744e-05 
WuU: 1.1890783e-19 
wyY: -0.03589321 
WaA: -0.0094145 
WvV: -0.5834950291600933
The sum of each par -->
w1: -1.1512744e-05 
WuU: 1.1890783e-19 
wyY: -0.04282949 
WaA: 0.06921042 
WvV: -0.4554335684326367
The sum of each par -->
w1: -1.1512744e-05 
WuU: 1.1890783e-19 
wyY: 0.0046821013 
WaA: -0.10789342 
WvV: -0.572260486989619
The sum of each par -->
w1: -1.1512744e-05 
WuU: 1.1890783e-19 
wyY: 0.012426332 
WaA: -0.04039937 
WvV: -0.8906791626517395
The sum of each par -->
w1: -1.1512744e-05 
WuU: 1.1890783e-19 
wyY: 0.045338497 
WaA: -0.32266167 
WvV: -0.3121710147231882
alpha------------ [-9.73145054e-08 -3.96942069e-07 -2.19470125e-07 -1.85253953e-08
 -5.15314199e-08 -3.56724572e-08 -7.46

In [41]:
#RS

In [44]:
#取出test的資料
testRS = np.zeros((test_amount,yt_test_amount)) #shape 150*20
target = np.zeros((test_amount,yt_test_amount))
#test_t 是true的
#test_f 是false的
        
for z in range(test_amount):
    user_id = test_idx[z]
    #positive target YouTuber list
    youtube_t = test_t[z] 
    #not target YouTuber list
    youtube_f = test_f[z]
    
    #前兩個放target的RS
    for i in range(len(youtube_t)):
        testRS[z][i] = RS[z][youtube_t[i]]
        target[z][i] = 1
    for i in range(len(youtube_f)):
        testRS[z][i+len(youtube_t)] = RS[z][youtube_f[i]]

In [45]:
print('Target\n',target)
print('Test RS\n',testRS)

Target
 [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Test RS
 [[ 2.46725865  1.04085854  2.02633018 -1.32373119 -1.17147989 -1.0298361
  -0.60236675 -1.27342202 -0.95329197 -0.63821749 -1.05381342 -1.56296745
  -1.49154191 -1.57881818 -1.52177903 -1.12520636 -1.47753735 -1.6509257
  -0.87691802 -0.7718031 ]
 [-0.70936621  0.47961396  0.62555488  2.25886024 -1.35017067 -1.36967896
   2.07284446 -2.12859433 -1.68

In [46]:
sumtarget = 0
for i in range(len(target)):
    #print(np.sum(target[i]))
    sumtarget += np.sum(target[i])
print('num of positive data in testing:',sumtarget)
print('total testing data:',test_amount*yt_test_amount)

num of positive data in testing: 45.0
total testing data: 200


In [47]:
def topN(sortlist,n):
    topList = []
    for i in range(n):
        topList.append(sortlist.index(max(sortlist)))
        #print(max(sortlist))
        #print(sortlist.index(max(sortlist)))
        sortlist[sortlist.index(max(sortlist))] = -1000000000
    return topList

In [48]:
count_0_all = []
for i in range(len(testRS)):
    top_0 = topN(list(testRS[i]),int(np.sum(target[i])))
    count_0_all.append(top_0)
    print(top_0)

acc_0 = 0
total = 0
for i in range(len(count_0_all)):
    for j in range(len(count_0_all[i])):
        #print(int(np.sum(target[i])))
        total+=int(np.sum(target[i]))
        if count_0_all[i][j] < int(np.sum(target[i])): #代表是0或1 (也就是target)
            acc_0 += 1
avg_acc = acc_0/100
print('avg_accuarcy for count_0:',avg_acc)
print(acc_0)

[0, 2, 1]
[3, 6, 2]
[1, 2, 13, 4, 5, 3, 17]
[1, 10, 8, 2, 5, 4]
[4, 1, 12]
[1, 15, 11]
[2, 1, 10, 0]
[3, 2, 5, 7, 4, 18]
[3, 18, 8, 5, 13]
[12, 16, 7, 0, 9]
avg_accuarcy for count_0: 0.24
24


# TOP1,TOP3,TOP5

In [49]:
def F1_score(prec,rec):
    f1 = (2*prec*rec)/(prec+rec)
    return f1

In [50]:
correct = 0
for i in range(len(testRS)):
    top_0 = topN(list(testRS[i]),1) #取一個
    count_0_all.append(top_0)
    print(top_0)
    if top_0[0] < int(np.sum(target[i])):
        correct += 1
top1_prec = correct/len(testRS)
top1_recall = correct/(sumtarget)
print('prec ',top1_prec,'recall ',top1_recall)
#f1 score
print('F1_score:',F1_score(top1_prec,top1_recall))

[0]
[3]
[1]
[1]
[4]
[1]
[2]
[3]
[3]
[12]
prec  0.7 recall  0.15555555555555556
F1_score: 0.2545454545454545


In [51]:
correct = 0
for i in range(len(testRS)):
    top_3 = topN(list(testRS[i]),3) #取一個
    count_0_all.append(top_3)
    #print(top_3)
    for j in range(len(top_3)):
        if top_3[j] < int(np.sum(target[i])):
            correct += 1
top3_prec = correct/(len(testRS)*3)
top3_recall = correct/(sumtarget)
print('prec ',top3_prec,'recall ',top3_recall)
#f1 score
print('F1_score:',F1_score(top3_prec,top3_recall))

prec  0.5 recall  0.3333333333333333
F1_score: 0.4


In [52]:
correct = 0
for i in range(len(testRS)):
    top_5 = topN(list(testRS[i]),5) #取一個
    count_0_all.append(top_5)
    #print(top_5)
    for j in range(len(top_5)):
        if top_5[j] < int(np.sum(target[i])):
            correct += 1
top5_prec = correct/(len(testRS)*5)
top5_recall = correct/(sumtarget)
print('prec ',top5_prec,'recall ',top5_recall)
#f1 score
print('F1_score:',F1_score(top5_prec,top5_recall))

prec  0.5 recall  0.5555555555555556
F1_score: 0.5263157894736842


# NDCG 

In [53]:
"""
NDCG
https://daiwk.github.io/posts/nlp-ndcg.html
"""
# pre_list
"""
test_amount = 150
yt_test_amount = 20
"""
all_sort = []
pre_matrix = np.zeros(shape=(test_amount,yt_test_amount))
for i in range(test_amount):
    top_5 = topN(list(testRS[i]),5) #取一個
    #print(top_5)
    all_sort.append(topN(list(testRS[i]),len(testRS[i])))
    for j in range(len(top_5)):
        pre_matrix[i][top_5[j]] = 1
        
#Ideal DCG，理想状况下的DCG。也就是说，相关性完全由高到低排序时算出的DCG：
def IDCG(ideal_list): #ideal_list example = [1,1,1,1,1,0,0,....]
    idcg=0
    for i in range(len(ideal_list)):
        #print((2**true_list[i]-1),math.log2(i+2))
        idcg+= (2**ideal_list[i]-1)/ math.log2(i+2)
    #print('idcg',idcg)
    return idcg
def DCG(prec_list): #找出前n名的[1,1,1,0,...]
    dcg=0
    for i in range(len(prec_list)):
        dcg+= (2**prec_list[i]-1)/ math.log2(i+2)
    #print('dcg',dcg)
    return dcg
total_ndcg = 0
num_ndcg = 5
for m in range(test_amount):
    idcg = IDCG([1]*num_ndcg)
    pre_list = []
    for s in all_sort[m][:num_ndcg]:
        #print(s)
        #print(target[m][s])
        pre_list.append(target[m][s])
    dcg = DCG(pre_list)
    ndcg = dcg/idcg
    #print(ndcg)
    total_ndcg += ndcg
avg_ndcg = total_ndcg/test_amount
print('NDCG:',avg_ndcg)

NDCG: 0.5354023477603981


# MAP

In [54]:
from sklearn.metrics import average_precision_score
"""
>>> y_true = np.array([0, 0, 1, 1])
>>> y_scores = np.array([0.1, 0.4, 0.35, 0.8])
>>> average_precision_score(y_true, y_scores)
"""
total_prec = 0
for u in range(test_amount):
    y_true = target[u]
    y_scores = pre_matrix[u]
    total_prec+=average_precision_score(y_true, y_scores)
MAP = total_prec/test_amount
print('MAP',MAP)

MAP 0.422047619047619
